#!/bin/bash

# Generate timestamped filename
timestamp=$(date +%Y-%m-%d_%H-%M-%S)
img_path="$HOME/Pictures/Screenshots/screenshot_$timestamp.png"

# Take fullscreen screenshot
grim "$img_path"

# Open in swappy for annotation
swappy -f "$img_path"

# Send notification
notify-send "📸 Fullscreen Screenshot" "Saved and copied to clipboard"

